apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - image: techbash.choudeshell.com/busybox
      name: busybox
      command: [ "sh", "-c"]
      args:
      - sleep 10000
      volumeMounts:
      - mountPath: /test
        name: test
    - image: techbash.choudeshell.com/busybox
      name: busybox2
      command: [ "sh", "-c"]
      args:
      - sleep 10000
      volumeMounts:
      - mountPath: /test
        name: test
  restartPolicy: Always
  volumes:
    - name: test
      emptyDir: {}