apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydata
spec:
  hostPath:
    path: /mnt/mydata      
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path