apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - image: busybox 
      name: busybox
      command: [ "sh", "-c"]
      args:
      - sleep 10000
  restartPolicy: Never

  # while sleep 0.01; do wget -q -O- http://php-apache; done