---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - image: techbash.choudeshell.com/busybox
      name: busybox
      command: [ "sh", "-c"]
      args:
      - sleep 10000
      envFrom:
        - secretRef: 
            name: my-secret
  restartPolicy: Never