apiVersion: batch/v1
kind: Job
metadata:
  name: sleep
spec:
  template:
    metadata:
      name: sleep
    spec:
      containers:
      - name: sleep
        image: techbash.choudeshell.com/busybox
        command: ["sleep",  "20"]
      restartPolicy: Never