apiVersion: batch/v1
kind: CronJob
metadata:
  name: sleep
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sleep
            image: techbash.choudeshell.com/busybox
            imagePullPolicy: IfNotPresent
            command: ["echo date"]             
          restartPolicy: OnFailure ####