apiVersion: v1
kind: Pod
metadata:
  name: nginx-probes
  labels:
    role: web
spec:
  containers:
  - name: nginx-probes
    image: techbash.choudeshell.com/nginx
    readinessProbe:
       httpGet:
            scheme: HTTPS
            path: /index.html
            port: 8443
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 20
      periodSeconds: 20