apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - image: busybox
      name: busybox
      command: [ "sh", "-c"]
      args:
      - echo 'stdout';>&2 echo "stderr";sleep 10000
  restartPolicy: Never