apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - image: busybox
      name: busybox
      command: [ "sh", "-c"]
      args:
      - sleep 10000
    - image: busybox
      name: busybox2
      command: [ "sh", "-c"]
      args:
      - sleep 10000
  restartPolicy: Never